# Program: ITY - Projekt 3
# Autor: Michal Cupák (xcupak04)
# Datum: 2011-03-29

#bib:
#	latex dokumentace.tex
#	bibtex dokumentace.aux
#	latex dokumentace.tex
#	latex dokumentace.tex
#	dvips -t a4 dokumentace.dvi
#	ps2pdf dokumentace.ps


tex2pdf:
	pdfcslatex dokumentace.tex
	pdfcslatex dokumentace.tex
	#vlna -l -n proj3.tex
	#latex proj3.tex
	#latex proj3.tex
	#dvips -t a4 proj3.dvi
	#ps2pdf proj3.ps
	#cp proj3.pdf ~/WWW/
